In [4]:
import numpy as np


In [2]:
k =np.array([[1,4,6],[3,33,23],[5,3,2]])
mean = np.argmax(k,axis =0)
# print(mean)
print(k-mean)

[[-1  3  5]
 [ 1 32 22]
 [ 3  2  1]]


In [3]:
Cx = 1/(k.shape[0]-1) * k.T @ k
Cx

array([[ 17.5,  59. ,  42.5],
       [ 59. , 557. , 394.5],
       [ 42.5, 394.5, 284.5]])

In [4]:
1/(3-1) * np.dot(k.T,k) #/ np.mean(k,axis=0)

array([[ 17.5,  59. ,  42.5],
       [ 59. , 557. , 394.5],
       [ 42.5, 394.5, 284.5]])

In [5]:
np.cov(k,rowvar=False,ddof=1)

array([[  4.        ,  -1.        ,  -4.        ],
       [ -1.        , 290.33333333, 187.83333333],
       [ -4.        , 187.83333333, 124.33333333]])

In [6]:
np.array_split(np.array([1,2,3,4,5,6,7,8,9]) , 4)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [5]:
X = np.random.randn(100,5)

In [6]:
cov = np.cov(X.T)
cov.shape

(5, 5)

In [15]:
class PCA:
    def __init__(self,n_component):
        self.mean=None
        self.n_component = n_component
        self.components = None
    def fit(self,x):
        #get mean
        self.mean = np.mean(x,axis=0)
        x = (x-self.mean)/ np.std(x,axis =0)
        cov = np.cov(x.T)
        e_val,e_vector = np.linalg.eig(cov)
        print(e_val)
        idx = np.argsort(e_val)[::-1]
        e_vector = e_vector[:,idx]
        print(e_vector.shape)
        self.component = e_vector[:self.n_component]
        print(self.component.shape)
    def transform(self,x):
        x = x-self.mean
        return np.dot(x,self.component.T)

%time  pca = PCA(2)        

%time pca.fit(X)
%time pca.transform(X)
,

CPU times: total: 0 ns
Wall time: 1.01 ms
[2.43826987 2.30209631 2.18205328 2.07859905 1.91523929 1.78083849
 1.72417948 1.65152406 1.62717096 1.52997928 1.49643572 1.35545535
 1.3214189  1.27106267 1.18430686 1.11085457 1.03144325 0.99257276
 0.1670253  0.17610448 0.92223606 0.87868656 0.23469684 0.27364853
 0.26776627 0.31172446 0.82416924 0.35923226 0.77291557 0.76087666
 0.40932659 0.41795422 0.46212127 0.69344991 0.66066934 0.50787839
 0.60797245 0.59361115 0.55245649 0.55601821]
(40, 40)
(2, 40)
CPU times: total: 0 ns
Wall time: 6.54 ms
CPU times: total: 0 ns
Wall time: 0 ns


''

In [11]:
X = np.random.randn(100,40)
class PCA:
    def __init__(self,n_component):
        self.mean = None
        self.n_component = n_component
        self.components = None

    def fit(self,X):
        self.mean = X.mean(axis=0)
        X = X - self.mean
        X = X/ np.std(X,axis=0)

        cov = np.cov(X.T)

        e_val,e_vectors =np.linalg.eig(cov)

        idx = np.argsort(e_val)[::-1]

        e_vectors = e_vectors[:,idx]

        self.components = e_vectors[:,:self.n_component]
        return self.components

    def transform(self,X):
        X = X-self.mean
        return np.dot(X,self.components)
x = np.random.randn(100,8)        
pca = PCA(2)        
pca.fit(x)
pca.transform(x)
,

''